#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     evm-wallet.js
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

const
  _libcrash =
  require(
    'crash-js');
/* global
     _cmdline_check */
const
  _cmdline_check =
    _libcrash._cmdline_check;
/* global
     _homedir_get */
const
  _homedir_get =
    _libcrash._homedir_get;
/* global
     _get_date_human */
const
  _get_date_human =
    _libcrash._get_date_human;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash._msg_info;
/* global
     _msg_error */
const
  _msg_error =
    _libcrash._msg_error;
/* global
     _argv_get */
const
_argv_get =
  _libcrash._argv_get;

const
  _libevm_wallet =
    require(
      "./libevm-wallet");
/* global
     _evm_wallet */
_evm_wallet =
  _libevm_wallet._evm_wallet;

function
  _global_variables() {
  /* global
       app_name:
         writable */
  app_name =
    "evm-wallet.js";
  /* global
       app_opts:
         writable */
  app_opts =
    [];
  /* global
       call_date:
         writable */
  call_date =
    "";
  /* global
       config_dir:
         writable */
  config_dir =
    "";
  /* global
       cache_dir:
         writable */
  cache_dir =
    "";
  /* global
       tasks_parallel:
         writable */
  tasks_parallel =
    "";
  /* global
       target_networks:
         writable */
  target_networks =
    [];
  /* global
       target_command:
         writable */
  target_command =
    "";
  /* global
       target_key:
         writable */
  target_key =
    "";
  /* global
       target_value:
         writable */
  target_value =
    "";
  /* global
       output_type:
         writable */
  output_type =
    "";
  /* global
       currency_type:
         writable */
  currency_type =
    "";
  /* global
       currency_address:
         writable */
  currency_address =
    "";
  /* global
       networks_all:
         writable */
  networks_all =
    "";
  /* global
       rpc_selection:
         writable */
  rpc_selection =
    "";
  /* global
       key_fingerprint:
         writable */
  key_fingerprint =
    "";
  /* global
       explorer_selection:
         writable */
  explorer_selection =
    "";
  /* global
       retries_max:
         writable */
  retries_max =
    "";
  /* global
       call_timeout:
         writable */
  call_timeout =
    "";
  /* global
       measure_unit:
         writable */
  measure_unit =
    "";
  /* global
       balance_lifespan:
         writable */
  balance_lifespan =
    "";
  qr_support =
    "";
  /* global
       quiet:
         writable */
  quiet =
    "";
}

function
  _tasks_parallel_auto_detect() {
  if ( networks_all == "y" ) {
    tasks_parallel =
      10;
  }
  else if ( networks_all == "n" ) {
    tasks_parallel =
      1;
  }
  else {
    _msg =
      `Invalid value '${tasks_parallel}' ` +
      `for variable '${tasks_parallel}'`;
  }
}

function
  _call_timeout_auto_detect() {
  if ( target_command == "get" ) {
    call_timeout =
      "30";
  }
  else {
    call_timeout =
      "300";
  }
}

function
  _target_key_auto_detect() {
  if ( target_command == "get" ) {
    target_key =
      "name";
  }
}

function
  _key_fingerprint_auto_detect() {
  if ( wallet_name != "" ) {
    // TODO:
    //   implement EVM GNUPG in Javascript
    true
  }
}

_output_type_check() {
  let
    _flag,
    _output_types,
    _type;
  _flag =
    "false";
  _output_types = [
    "",
    "name",
    "address",
    "fingerprint"
  ];
  for ( _type of _output_types ) {
    if ( output_type == _type ) {
      _flag =
        "true";
      break
    }
  }
  if ( flag == "false" ) {
    _msg =
      `Invalid output type '${output_type}'.`;
  }
}

function 
  _overrides_set() {
  if ( call_date == "" ) {
    call_date =
      _get_date_human();
  }
  if ( target_command == "" ) {
    target_command =
      "get";
  }
  if ( networks_all == "" ) {
    networks_all =
      "n";
  }
  _tasks_parallel_auto_detect();
  _call_timeout_auto_detect();
  if ( config_dir == "" ) {
    config_dir =
      `${_homedir_get()}/.config/evm-wallet`;
  }
  if ( target_networks.length < 1 &&
       networks_all == "n" ) {
    target_networks.push(
      100);
  }
  _target_key_auto_detect();
  if ( balance_lifespan == "" ) {
    balance_lifespan =
      "3600";
  }
  if ( retries_max == "" ) {
    retries_max =
      "2";
  }
  if ( measure_unit == "" ) {
    measure_unit =
      "ether";
  }
  if ( currency_type == "" ) {
    if ( currency_address == "" ) {
      currency_type =
        "gas";
    }
    else if ( currency_address != "" ) {
      currency_type =
        "erc20";
    }
  }
  if ( rpc_selection == "" ) {
    // TODO:
    //   remove all references to that
    //   monster
    rpc_selection =
      "kirsh";
  }
  if ( explorer_selection == "" ) {
    // TODO:
    //   remove all references to that
    //   humunculus
    explorer_selection =
      "kirsh";
  }
  // TODO:
  //   explorers api keys, optional frankly
  //   since theres the evm-contracts-source-index
  _wallet_overrides_set( 
    "evm-wallet",
    wallet_name,
    "y",
    "n");
  _key_fingerprint_auto_detect();
  _output_type_check();
  // See https://github.com/openpgpjs/openpgpjs/issues/2004
  if ( qr_support == "" ) {
    qr_support =
      "n";
  }
}

function
  _config_show() {
  let
    _line,
    _text;
  _text = [
    `${app_name} configuration:`,
    `      Runtime environment:   ${runtime_environment}`,
    `          Encoding format:   ${encoding_format}`,
    `              Buffer size:   ${buffer_size}`,
    `      Chunk string length:   ${string_length}`,
    `       Chunks amount only:   ${amount_only}`,
    `                  In file:   ${in_file}`,
    `          Out text prefix:   ${out_txt_prefix}`,
  ];
  for ( _line of _text ) {
    _msg_info(
      _line);
  }
}

function
  _usage(
    _exit_code) {
  let
    _line,
    _text;
  _text = [
    "Converts binary to ascii text.",
    "",
    "Usage:",
    "",
    "  bin2txt",
    "    <in-file>",
    "    <out-txt-prefix>",
    "",
    "  arguments:",
    "    <in-file>                        An input file.",
    "    <out-file-prefix>                Prefix for the output file(s).",
    "",
    "  options:",
    "",
    "     -f --encoding-format            Encoding format ('base64').",
    `       <encoding-format>             Default: '${encoding_format}`,
    "",
    "     -B --buffer-size                Size in bytes the input file will",
    "       <buffer-size>                 be split before being read",
    "                                     in memory and passed to",
    "                                     the encoder.",
    `                                     Default: '${buffer_size}'`,
    "",
    "     -L --string-length              String chunk length.",
    `       <string-length>               Default: '${string_length}'`,
    "",
    "     -s --amount-only                Only print chunks amount.",
    `                                     Default: '${amount_only}'`,
    "",
    "     -h --help                       This message.",
    "     -v --verbose                    Enable verbose output."
  ];
  for ( _line of _text ) {
    console.log(
      _line);
  }
  process.exit(
    _exit_code);
}

function 
  _cmdline_parse() {
  let
    _argv,
    _help_display,
    _msg;
  _argv =
    _argv_get();
  _options =
    _argv[
      "_"];
  quiet = 
    "y";
  runtime_environment =
    "node";
  if ( _options.indexOf(
         "--help") > -1 ||
       _options.indexOf(
         "-h") > -1) {
    _help_display =
      true;
  }
  if ( _help_display ) {
    quiet =
      "n";
    _usage(
      0);
  }
  if ( typeof(
         _argv) == "undefined" ||
       _argv[
         "_"].length < 1 ) {
    _msg =
      "Input file argument required.";
    _msg_error(
      _msg,
      0);
    _usage(
      1);
  }
  in_file =
    _argv[
      "_"][
        0];
  if ( _argv[
         "_"].length < 2 ) {
    out_txt_prefix =
      in_file +
      ".base64";
  }
  if ( "L" in _argv ) {
    string_length =
      _argv[
        "L"];
  }
  if ( "string-length" in _argv ) {
    string_length =
      _argv[
        "string-length"];
  }
  if ( "s" in _argv ) {
    amount_only =
      _argv[
        "s"];
  }
  if ( "amount-only" in _argv ) {
    amount_only =
      _argv[
        "amount-only"];
  }
  if ( "v" in _argv ) {
    verbose =
      _argv[
        "v"];
  }
  if ( "verbose" in _argv ) {
    verbose =
      _argv[
        "verbose"];
  }
  if ( verbose ) {
    quiet =
      "n";
  }
}

function
  _url_parse() {
  let
    _argv;
  runtime_environment =
    "browser";
  _argv =
    _argv_url_get();
  in_file =
    _argv_url_get(
      "in_file")[
        0];
  target_planet =
    _argv_url_get(
      "out_txt_prefix")[
        0];
  quiet =
    _argv_url_get(
      "quiet");
  if ( quiet.length === 0 ) {
    quiet =
      "n";
  }
}

_global_variables();
if ( _cmdline_check(
       "bin2txt.js") == true ) {
  _cmdline_parse();
}
_overrides_set();
_config_show();
app_opts = [
  in_file,
  out_txt_prefix,
  encoding_format,  
  string_length,
  buffer_size,
  amount_only 
];
_bin2txt.apply(
  null,
  app_opts);
