#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     evm-wallet.js
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

const
  _libcrash =
  require(
    'crash-js');
/* global
     _cmdline_check */
const
  _cmdline_check =
    _libcrash._cmdline_check;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash._msg_info;
/* global
     _msg_error */
const
  _msg_error =
    _libcrash._msg_error;
/* global
     _argv_get */
const
_argv_get =
  _libcrash._argv_get;

const
  _libevm_wallet =
    require(
      "./libevm-wallet");
/* global
     _evm_wallet */
_evm_wallet =
  _libevm_wallet._evm_wallet;

function
  _global_variables() {
  /* global
       app_name:
         writable */
  app_name =
    "evm-wallet.js";
  /* global
       app_opts:
         writable */
  app_opts =
    [];
  /* global
       encoding_format:
         writable */
  encoding_format =
    "";
  /* global
       buffer_size:
         writable */
  buffer_size =
    "";
  /* global
       string_length:
         writable */
  string_length =
    "";
  /* global
       in_file:
         writable */
  in_file =
    "";
  /* global
       out_txt_prefix:
         writable */
  out_txt_prefix =
    "";
  /* global
       amount_only:
         writable */
  amount_only =
    "";
  /* global
       quiet:
         writable */
  quiet =
    "";
}

function 
  _overrides_set() {
  if ( encoding_format == "" ) {
    encoding_format =
      "base64";
  }
  if ( string_length == "" ) {
    string_length =
      "10000";
  }
  if ( buffer_size == "" ) {
    buffer_size =
      "2000000"; // 2MB
  }
  if ( amount_only == "" ) {
    amount_only =
      "false";
  }
}

function
  _config_show() {
  let
    _line,
    _text;
  _text = [
    `${app_name} configuration:`,
    `      Runtime environment:   ${runtime_environment}`,
    `          Encoding format:   ${encoding_format}`,
    `              Buffer size:   ${buffer_size}`,
    `      Chunk string length:   ${string_length}`,
    `       Chunks amount only:   ${amount_only}`,
    `                  In file:   ${in_file}`,
    `          Out text prefix:   ${out_txt_prefix}`,
  ];
  for ( _line of _text ) {
    _msg_info(
      _line);
  }
}

function
  _usage(
    _exit_code) {
  let
    _line,
    _text;
  _text = [
    "Converts binary to ascii text.",
    "",
    "Usage:",
    "",
    "  bin2txt",
    "    <in-file>",
    "    <out-txt-prefix>",
    "",
    "  arguments:",
    "    <in-file>                        An input file.",
    "    <out-file-prefix>                Prefix for the output file(s).",
    "",
    "  options:",
    "",
    "     -f --encoding-format            Encoding format ('base64').",
    `       <encoding-format>             Default: '${encoding_format}`,
    "",
    "     -B --buffer-size                Size in bytes the input file will",
    "       <buffer-size>                 be split before being read",
    "                                     in memory and passed to",
    "                                     the encoder.",
    `                                     Default: '${buffer_size}'`,
    "",
    "     -L --string-length              String chunk length.",
    `       <string-length>               Default: '${string_length}'`,
    "",
    "     -s --amount-only                Only print chunks amount.",
    `                                     Default: '${amount_only}'`,
    "",
    "     -h --help                       This message.",
    "     -v --verbose                    Enable verbose output."
  ];
  for ( _line of _text ) {
    console.log(
      _line);
  }
  process.exit(
    _exit_code);
}

function 
  _cmdline_parse() {
  let
    _argv,
    _help_display,
    _msg;
  _argv =
    _argv_get();
  _options =
    _argv[
      "_"];
  quiet = 
    "y";
  runtime_environment =
    "node";
  if ( _options.indexOf(
         "--help") > -1 ||
       _options.indexOf(
         "-h") > -1) {
    _help_display =
      true;
  }
  if ( _help_display ) {
    quiet =
      "n";
    _usage(
      0);
  }
  if ( typeof(
         _argv) == "undefined" ||
       _argv[
         "_"].length < 1 ) {
    _msg =
      "Input file argument required.";
    _msg_error(
      _msg,
      0);
    _usage(
      1);
  }
  in_file =
    _argv[
      "_"][
        0];
  if ( _argv[
         "_"].length < 2 ) {
    out_txt_prefix =
      in_file +
      ".base64";
  }
  if ( "L" in _argv ) {
    string_length =
      _argv[
        "L"];
  }
  if ( "string-length" in _argv ) {
    string_length =
      _argv[
        "string-length"];
  }
  if ( "s" in _argv ) {
    amount_only =
      _argv[
        "s"];
  }
  if ( "amount-only" in _argv ) {
    amount_only =
      _argv[
        "amount-only"];
  }
  if ( "v" in _argv ) {
    verbose =
      _argv[
        "v"];
  }
  if ( "verbose" in _argv ) {
    verbose =
      _argv[
        "verbose"];
  }
  if ( verbose ) {
    quiet =
      "n";
  }
}

function
  _url_parse() {
  let
    _argv;
  runtime_environment =
    "browser";
  _argv =
    _argv_url_get();
  in_file =
    _argv_url_get(
      "in_file")[
        0];
  target_planet =
    _argv_url_get(
      "out_txt_prefix")[
        0];
  quiet =
    _argv_url_get(
      "quiet");
  if ( quiet.length === 0 ) {
    quiet =
      "n";
  }
}

_global_variables();
if ( _cmdline_check(
       "bin2txt.js") == true ) {
  _cmdline_parse();
}
_overrides_set();
_config_show();
app_opts = [
  in_file,
  out_txt_prefix,
  encoding_format,  
  string_length,
  buffer_size,
  amount_only 
];
_bin2txt.apply(
  null,
  app_opts);
