#!/usr/bin/env node


// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     libevm-wallet
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the
 *     GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */


const
  _crash_js_module =
    require(
      "crash-js");
/* global
     _file_exists */
const
  _file_exists =
    _crash_js_module._file_exists;
/* global
     _mkdir */
const
  _mkdir =
    _crash_js_module._mkdir;
/* global
     _msg_info */
const
  _msg_info =
    _crash_js_module._msg_info;
/* global
     _msg_error */
const
  _msg_error =
    _crash_js_module._msg_error;
/* global
     _path_join */
const
  _path_join =
    _crash_js_module._path_join;
const
  _evm_chains_info_module =
    require(
      "evm-chains-info");
/* global
     _evm_chains_info */
const
  _evm_chains_info =
    _evm_chains_info_module._evm_chains_info;
const
  _address_get_module =
    require(
      "./lib/address-get");
/* global
     _address_get */
const
  _address_get =
    _address_get_module._address_get;
const
  _balance_check_module =
    require(
      "./lib/balance-check");
/* global
     _balance_check */
const
  _balance_check =
    _balance_check_module._balance_check;
/* global
     _msg_error_balance_insufficient */
const
  _msg_error_balance_insufficient =
    _balance_check_module._msg_error_balance_insufficient;
const
  _balance_get_module =
    require(
      "./lib/balance-get");
/* global
     _balance_get */
const
  _balance_get =
    _balance_get_module._balance_get;
const
  _balance_send_module =
    require(
      "./lib/balance-send");
/* global
     _balance_send */
const
  _balance_send =
    _balance_send_module._balance_send;
const
  _ethers_to_wei_module =
    require(
      "./lib/ethers-to-wei");
/* global
     _ethers_to_wei */
const
  _ethers_to_wei =
    _ethers_to_wei_module._ethers_to_wei;
const
  _network_provider_module =
    require(
      "./lib/network-provider");
/* global
     _provider_get */
const
  _provider_get =
    _network_provider_module._provider_get;
/* global
     _msg_info_provider_generated */
const
  _msg_info_provider_generated =
    _network_provider_module._msg_info_provider_generated;
const
  _price_gas_get_module =
    require(
      "./lib/price-gas-get");
/* global
     _price_gas_get */
const
  _price_gas_get =
    _price_gas_get_module._price_gas_get;
const
  _price_gas_transaction_get_module =
    require(
      "./lib/price-gas-transaction-get");
/* global
     _price_gas_transaction_get */
const
  _price_gas_transaction_get =
    _price_gas_transaction_get_module._price_gas_transaction_get;
const
  _seed_new_module =
    require(
      "./lib/seed-new");
/* global
     _seed_new */
const
  _seed_new =
    _seed_new_module._seed_new;
const
  _wallet_get_module =
    require(
      "./lib/wallet-get");
/* global
     _wallet_get */
const
  _wallet_get =
    _wallet_get_module._wallet_get;
const
  _wallet_new_module =
    require(
      "./lib/wallet-new");
/* global
     _wallet_new */
const
  _wallet_new =
    _wallet_new_module._wallet_new;

async function
  _evm_wallet(
    _target_command,
    _wallet_name,
    _wallet_path,
    _wallet_password,
    _wallet_seed,
    _key_fingerprint,
    _config_dir,
    _cache_dir,
    _networks_all,
    _rpc_selection,
    _api_key,
    _retries_max,
    _tasks_parallel,
    _call_timeout,
    _measure_unit,
    _balance_lifespan,
    _currency_type,
    _currency_address,
    _output_type,
    _target_key,
    _target_value,
    _target_networks) {
  let
    _args,
    _msg,
    _rpc,
    _target_network,
    _tx,
    _receipt;
  const
    _cmd =
      "";
  if ( typeof(
         _target_networks) == "undefined" ||
       _target_networks == [] ||
       _target_networks == "" ) {
    _target_networks =
      [];
  }
  if ( 0 < _target_networks.length ) {
    _target_network =
      _target_networks[
        0];
  }
  else {
    _target_network =
      "";
  }
  if ( typeof(
         _target_network) == "string" ) {
    if ( _target_network.startsWith(
           "https://") ) {
      _rpc =
        _target_network;
    }
  }
  if ( typeof(
         _target_network) == "number" ||
       ( ! _target_network.startsWith(
           "https://") ) ) {
    const
      _evm_chains_info_args = [
        "get",            // command
        "id",             // input type 
        "rpc",            // output type
        "offline",        // retrieval method
        [ "node",         // db types
          "system" ],
        "kirsh",          // selection method
        "",               // api key
        "n",              // all networks
        _target_network,
        []                // db paths
      ];
    _rpc =
      _evm_chains_info.apply(
        null,
        _evm_chains_info_args)[
        0];
  }
  _msg =
    `Using RPC address '${_rpc}'.`;
  _msg_info(
    _msg);
  if ( _target_command == "get" ) {
    if ( _target_key == "balance" ) {
      const
        _balance_dir =
          _path_join( [
            _cache_dir,
            _wallet_name,
            _target_network.toString() ]);
      const
        _balance_file =
          _path_join( [
            _balance_dir,
            "balance"]);
      if ( ! _file_exists(
               _balance_dir) ) {
        _mkdir(
          _balance_dir,
          { "recursive":
              true });
      }
      const
        _balance_get_args = [
          _wallet_seed,
          _rpc,
          _api_key,
          "",                  // Target address, using seed
          _measure_unit,
          _balance_file,
          _retries_max
        ];
      const
        _balance =
          await _balance_get.apply(
            null,
            _balance_get_args);
      return _balance;
    }
    else if ( _target_key == "address" ) {
      const
        _address_get_args = [
          _wallet_seed,
          "",                 // Network
          "",                 // API Key
          "",                 // Chain ID
          "",                 // Chain name
          ""                  // Output file
        ];
      const
        _wallet_address =
          _address_get.apply(
            null,
            _address_get_args);
      return _wallet_address;
    }
    else {
      _msg =
        `Unknown key '${_target_key}'.`;
      _msg_info(
        _msg);
    }
  }
  else if ( _target_command == "send" ) {
    const
      _target_address =
        _target_key;
    const
      _target_amount =
        _target_value;
    if ( _currency_type == "gas" ) {
      const
        _balance_send_args = [
          _wallet_seed,
          _target_address,
          _target_amount,
          _rpc,
          _api_key,
          _measure_unit
	];
      [ _tx,
        _receipt ] =
        await _balance_send.apply(
          null,
          _balance_send_args);
      return [ _tx,
               _receipt ];
    }
    else if ( _currency_type == "erc20" ) {
      const
        _erc20_tools_module =
          require(
            "erc20-tools");
      const
        _token_send =
          _erc20_tools_module._token_send;
      const
        _token_send_args = [
          _retries_max,
          _call_timeout,
          _wallet_seed,
          _api_key,
          _rpc,                          // NOTE: data filled-in
          _currency_address,             // by 'token-send':
          "",                            //   erc20 abi
          "",                            //   erc20 bytecode
          "",                            //   erc20 hardhat artifact
          _measure_unit,
          "",                            // output path
          _target_address,
          _target_amount
	];
      const
        _token_sent =
          await _token_send.apply(
            null,
            _token_send_args);
      return _token_sent;
    }
    else {
      _msg =
        `Unknown currency type '${_currency_type}'.`;
    }
  }
  else if ( _target_command == "run" ) {
    true;
  }
  else {
    _msg =
      `Unknown command '${_target_command}'.`;
    _msg_error(
      _msg,
      1);
  }
}

module.exports = {
  _address_get:
    _address_get,
  _balance_check:
    _balance_check,
  _msg_error_balance_insufficient:
    _msg_error_balance_insufficient,
  _balance_get:
    _balance_get,
  _balance_send:
    _balance_send,
  _evm_wallet:
    _evm_wallet,
  _ethers_to_wei:
    _ethers_to_wei,
  _provider_get:
    _provider_get,
  _msg_info_provider_generated:
    _msg_info_provider_generated,
  _price_gas_get:
    _price_gas_get,
  _price_gas_transaction_get:
    _price_gas_transaction_get,
  _seed_new:
    _seed_new,
  _wallet_get:
    _wallet_get,
  _wallet_new:
    _wallet_new
};
